development:
   adapter: mysql2
   database: dashboard_db_development
   username: root
   password: password
   host: localhost
  
test:
   adapter: mysql2
   database: dashboard_db_test
   username: root
   password: password
   host: localhost
   
production:
   adapter: mysql2
   database: dashboard_db_production
   username: root
   password: password
   host: localhost